
#This file should contain something like...

#- Servo IDs
#- Joint names
#- Joint limits
#- control loop rate

cobot_control:
  ros__parameters:
    control_rate: 50  # Hz

    joints:
      shoulder_pan:
        servo_id: 1
        min_degrees: -90
        max_degrees: 90
      shoulder_tilt:
        servo_id: 2
        min_degrees: -90
        max_degrees: 90
      elbow:
        servo_id: 3
        min_degrees: -135
        max_degrees: 135
      wrist:
        servo_id: 4
        min_degrees: -90
        max_degrees: 90